import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

path = [cwd, cwd + '/MK20DX256VLL/inc']
src = Split("""
system_MK20D7.c
MK20DX256VLL/drivers/flexbus.c
MK20DX256VLL/drivers/port.c
""")

#add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
     src = src + ['TOOLCHAIN_GCC_ARM/startup_MK20DX256VLL.S']
     src = src + ['TOOLCHAIN_GCC_ARM/startup.c']
     
     path += [cwd + 'TOOLCHAIN_GCC_ARM']
elif rtconfig.CROSS_TOOL == 'keil':
     src = src + ['TOOLCHAIN_ARM_STD/startup_MK20D7.s']
# elif rtconfig.CROSS_TOOL == 'iar':

#CPPDEFINES = ['']
group = DefineGroup('Device', src, depend = [''], CPPPATH = path)
#CPPDEFINES = CPPDEFINES)

Return('group')
