import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

path = [cwd, cwd + '/MK20DX256VLL/inc']
#src = Glob('MK20DX256VLL/drivers/*.c')

#add for startup script 
if rtconfig.CROSS_TOOL == 'gcc':
     src = ['TOOLCHAIN_GCC_ARM/startup_MK20DX256VLL.S']
     src = src + ['TOOLCHAIN_GCC_ARM/startup.c']
     src = src + ['TOOLCHAIN_GCC_ARM/system_MK20D7.c']
     path += [cwd + 'TOOLCHAIN_GCC_ARM']
elif rtconfig.CROSS_TOOL == 'keil':
     src = src + ['TOOLCHAIN_ARM_STD/startup_MK64F12.s']
# elif rtconfig.CROSS_TOOL == 'iar':

#CPPDEFINES = ['']
group = DefineGroup('Device', src, depend = [''], CPPPATH = path)
#CPPDEFINES = CPPDEFINES)

Return('group')
