language: c

notifications:
  email: false

before_script:
  - sudo apt-get -qq update
  - sudo apt-get -qq install clang gcc-multilib libc6:i386 libgcc1:i386 gcc-4.6-base:i386 libstdc++5:i386 libstdc++6:i386 libsdl-dev
  - git clone --depth 1 https://github.com/RT-Thread/rt-thread.git $HOME/rt-thread
  - export RTT_ROOT=$HOME/rt-thread

script:
  - scons -k

env:
  - RTT_CC='gcc'
  - RTT_CC='clang-analyze'
