Import('RTT_ROOT')
from building import *

src = Split("""
src/avprofile.c
src/b64.c
src/event.c
src/jitterctl.c
src/logging.c
src/netsim.c
src/ortp.c
src/ortp_srtp.c
src/payloadtype.c
src/port.c
src/posixtimer.c
src/rtcp.c
src/rtcpparse.c
src/rtpparse.c
src/rtpprofile.c
src/rtpsession.c
src/rtpsession_inet.c
src/rtpsignaltable.c
src/rtptimer.c
src/scheduler.c
src/sessionset.c
src/str_utils.c
src/telephonyevents.c
src/utils.c
src/zrtp.c
src/rand.c
""")

test_src = Split("""
tests/mrtprecv.c
tests/mrtpsend.c
tests/rtpmemtest.c
tests/rtprecv.c
tests/rtpsend.c
tests/rtpsend_stupid.c
tests/test_timer.c
tests/tevmrtprecv.c
tests/tevrtprecv.c
tests/tevrtpsend.c
""")


# The set of source files associated with this SConscript file.
path = [GetCurrentDir() + '/src',
    GetCurrentDir() + '/include']

if GetDepend(['RT_ORTP_TEST']):
    src += test_src


group = DefineGroup('ORTP', src, depend = ['RT_USING_ORTP'], CPPPATH = path)

Return('group')
